<a href="https://colab.research.google.com/github/rodrigoviannini/Machine-Learning/blob/main/Algoritmo_de_Naive_Bayes_aplicado_em_risco_de_credito.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importação das bibliotecas necessarias.

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.preprocessing import StandardScaler

In [ ]:
# Importando os dados e vizualizando
base__risco_credito = pd.read_csv("/content/risco_credito.csv")
base__risco_credito

historia divida garantias     renda     risco
0           ruim   alta   nenhuma      0_15      alto
1   desconhecida   alta   nenhuma     15_35      alto
2   desconhecida  baixa   nenhuma     15_35  moderado
3   desconhecida  baixa   nenhuma  acima_35      alto
4   desconhecida  baixa   nenhuma  acima_35     baixo
5   desconhecida  baixa  adequada  acima_35     baixo
6           ruim  baixa   nenhuma      0_15      alto
7           ruim  baixa  adequada  acima_35  moderado
8            boa  baixa   nenhuma  acima_35     baixo
9            boa   alta  adequada  acima_35     baixo
10           boa   alta   nenhuma      0_15      alto
11           boa   alta   nenhuma     15_35  moderado
12           boa   alta   nenhuma  acima_35     baixo
13          ruim   alta   nenhuma     15_35      alto

# Divisão entre classes e previsões

In [ ]:
# Variavel para armazenar os atributos previsores
x_risco_credito = base__risco_credito.iloc[:, 0:4].values

'''O .values() é para que seja convertido para numpy, para que as bibliotecas entendam'''

# Variavel para armazenar a classe
y_risco_credito = base__risco_credito.iloc[:, 4].values

In [ ]:
# Verificando se foi feito corretamente a divisão das bases
x_risco_credito

array([['ruim', 'alta', 'nenhuma', '0_15'],
       ['desconhecida', 'alta', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'adequada', 'acima_35'],
       ['ruim', 'baixa', 'nenhuma', '0_15'],
       ['ruim', 'baixa', 'adequada', 'acima_35'],
       ['boa', 'baixa', 'nenhuma', 'acima_35'],
       ['boa', 'alta', 'adequada', 'acima_35'],
       ['boa', 'alta', 'nenhuma', '0_15'],
       ['boa', 'alta', 'nenhuma', '15_35'],
       ['boa', 'alta', 'nenhuma', 'acima_35'],
       ['ruim', 'alta', 'nenhuma', '15_35']], dtype=object)

In [ ]:
# Verificando se foi feito corretamente a divisão das bases
y_risco_credito

array(['alto', 'alto', 'moderado', 'alto', 'baixo', 'baixo', 'alto',
       'moderado', 'baixo', 'baixo', 'alto', 'moderado', 'baixo', 'alto'],
      dtype=object)

# Preparando os dados com LabelEncoder

In [ ]:
# Importando LabelEncoder
from sklearn.preprocessing import LabelEncoder

In [ ]:
label_encoder_historia = LabelEncoder()
label_encoder_divida = LabelEncoder()
label_encoder_garantias = LabelEncoder()
label_encoder_renda = LabelEncoder()

In [ ]:
x_risco_credito[: , 0] = label_encoder_historia.fit_transform(x_risco_credito[: , 0])
x_risco_credito[: , 1] = label_encoder_divida.fit_transform(x_risco_credito[: , 1])
x_risco_credito[: , 2] = label_encoder_garantias.fit_transform(x_risco_credito[: , 2])
x_risco_credito[: , 3] = label_encoder_renda.fit_transform(x_risco_credito[: , 3])

In [ ]:
# Verificando o resultado
x_risco_credito

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 1, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [ ]:
# Salvando as variaveis.
import pickle 
with open('risco_credito.pkl', 'wb' ) as f:
  pickle.dump([x_risco_credito, y_risco_credito], f)

## Criando o algoritmo NAIVE BAYES

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
naive_risco_credito = GaussianNB()

# Criando tabela de probabilidade
naive_risco_credito.fit(x_risco_credito, y_risco_credito)

GaussianNB()

# Fazendo a previsão

Cliente para testes

1.  Historia de credito = boa [0] | Divida Alta = [0] | Garantia Nenhuma = [1] | Renda > 35 = [2]

2.  Historia de credito = ruim [2] | Divida Alta = [0] | Garantia Adequada = [0] | Renda < 15 = [0]



In [ ]:
# Criando a previsão do credito dos clientes de teste acima
previsao = naive_risco_credito.predict([[0, 0, 1, 2], [2, 0, 0, 0]])

In [ ]:
# Observando a previsão de credito criada para os clientes
previsao

array(['baixo', 'moderado'], dtype='<U8')

# Observando os atributos utilizados no NAIVE BAYES

In [ ]:
# verificando as classes da classificação
naive_risco_credito.classes_

array(['alto', 'baixo', 'moderado'], dtype='<U8')

In [ ]:
# Observando quantos registros temos em cada classe segundo o Dataset
naive_risco_credito.class_count_

array([6., 5., 3.])

In [ ]:
# Observando as probabilidades em priori
# Esses dados nos mostram a porcentagem de cada classe nos registros
naive_risco_credito.class_prior_

array([0.42857143, 0.35714286, 0.21428571])